name: Node.js Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Commit and push changes
      run: |
        git config --global user.email "marcell.gimesi@gmail.com"
        git config --global user.name "marcellgim"
        git add dist/*.js
        git commit -m "Update build via GitHub Actions"
        git push
